### ISSUE TITLE
Python examples using directly `magnum`

### ISSUE THREAD

**Issue by c-joly** [NOSALRO/robot_dart#210]
Hi @costashatz , here is an issue linked to the JOSS review https://github.com/openjournals/joss-reviews/issues/6771

Some python examples are directly importing the module `magnum` (e.g. `sensors_tutorial.py`). However, the bindings of `magnum` are not installed by the scripts (both Linux and MacOS). Should we consider these examples as depreciated? If not, can you please update the install scripts to compile and install the bindings of `magnum`?

**Comment by costashatz** [comment]
@c-joly feel free to re-open the issue if #217  did not fix this :) Thanks again!
