### ISSUE TITLE
Releases and changleog

### ISSUE THREAD

**Issue by costashatz** [NOSALRO/robot_dart#50]
I think we should start organizing for releases and a changelog.

**Comment by costashatz** [comment]
I propose a release scheme as follows:

- We do a release only when we really have something to release or when minor patches stay in master for more than 2-3 months
- Release versioning: major.minor.patch; we start from v1.0.0 once we finish this restructure
    - we increment the major number when we have API breakage (even if we keep backward compatibility)
    - we increment the minor number when we have serious bug-fixes or important new features
    - we increment the patch number for everything else (e.g., fix of corner-cases, minor new features etc.)
- Changelog
    - Every PR to be merged should add changelog
    - We begin keeping track of changes after v1.0.0 (this iteration)

@jbmouret @dalinel @PedroDesRobots @Aneoshun  Let me know if you agree or have anything to add.

**Comment by Aneoshun** [comment]
Thanks Konstantinos, 

Sounds good to me.

**Comment by costashatz** [comment]
Closed by #145
